package com.Q3;

public class Main {
	//Checked exceptions occur at compile time.			
	//These types of exceptions can be handled at the time of compilation.	
	//Here, the JVM needs the exception to catch and handle.
	
	//Unchecked exceptions occur at runtime.
	//These types of exceptions cannot be a catch or handle at the time of compilation, because they get generated by the mistakes in the program.
	//Here, the JVM does not require the exception to catch and handle.
	
	//Difference between throw and throws in java..
	
	// With throw keyword we can generate the exception class object in our program explicitly.
	// Generally jvm will create the exception class object whenever logical error occurs in our application.
	
	//the throws keyword in Java is used to declare exceptions that can occur during the execution of a program. 
	//For any method that can throw exceptions, it is mandatory to use the throws keyword to list the exceptions that can be thrown.
	
}
